apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: email-virtual
spec:
  hosts:
    - email # ім'я Service до якого застосовується налаштування
  http:
    - route:
        - destination:
            host: email # ім'я Service до якого застосовується налаштування
      timeout: 15s
      retries:
        attempts: 3
        retryOn: 5xx
        perTryTimeout: 5s