apiVersion: batch/v1
kind: Pod
metadata:
  name: service1
spec:
  template:
    metadata:
      name: service1-pod
    spec:
      containers:
      - name: service1
        image: secret333boy/service1:1.0