apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
type: Opaque
data:
  PASSWORD_SALT: JDJiJDEwJG9rd3pXU0U4MmtlN1k4SDIudUF1dXU=
  ACCESS_TOKEN_SECRET: QUNDRVNTX1RPS0VOX1NFQ1JFVA==
  REFRESH_TOKEN_SECRET: UkVGUkVTSF9UT0tFTl9TRUNSRVQ=
  POSTGRES_DB: cG9zdGdyZXM=
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=