apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-pod
  template:
    metadata:
      labels:
        app: auth-pod
    spec:
      containers:
        - image: secret333boy/auth:1.4
          name: auth-container
          ports:
            - containerPort: 8082
          env:
            - name: GATEWAY_URL
              value: "http://localhost:80"
            - name: PASSWORD_SALT
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: PASSWORD_SALT
            - name: ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: ACCESS_TOKEN_SECRET
            - name: REFRESH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: REFRESH_TOKEN_SECRET
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: POSTGRES_PASSWORD
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
