CREATE TABLE IF NOT EXISTS TICKETS (
    ID bigserial NOT NULL,
    PRICE decimal(10, 2) NOT NULL,
    USER_ID bigint DEFAULT NULL,
    SESSION_ID bigint,
    PLACE_ID bigint,
    CONSTRAINT PK_TICKET PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS SESSIONS (
     ID bigserial NOT NULL,
     MOVIE_ID bigint,
     HALL_ID bigint,
     START_TIME date,
     END_TIME date,
     CONSTRAINT PK_SESSION PRIMARY KEY (ID)
);

ALTER TABLE TICKETS ADD CONSTRAINT FK_TICKET_ON_SESSION
    FOREIGN KEY (SESSION_ID) REFERENCES SESSIONS (ID);