replicaCount: 1

image:
  name: zaranik/booking-service:2.3
  port: 8084

service:
  ports:
    - name: http
      port: 80
      containerPort: 8084

resources:
  limits:
    memory: "512Mi"
    cpu: "500m"

env:
  - name: POSTGRES_DB
    type: secret
    value: POSTGRES_DB
  - name: POSTGRES_USER
    type: secret
    value: POSTGRES_USER
  - name: POSTGRES_PASSWORD
    type: secret
    value: POSTGRES_PASSWORD

ingress:
  mapping: /api/booking

db:
  port: 5432

postgresql:
  nameOverride: booking-postgres
  fullnameOverride: booking-postgres
  postgresqlDatabase: "booking-service"
  postgresqlUsername: "postgres"
  postgresqlPassword: "postgres"
  postgresqlPostgresPassword: "postgres"
  persistence:
    size: 1Gi
    mountPath: /var/lib/postgresql/data
