server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/booking-servoce
    username: admin
    password: admin
  jpa:
    hibernate:
#      ddl-auto: update
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect