server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://${BOOKING_POSTGRES_SERVICE_HOST:localhost}:${BOOKING_POSTGRES_SERVICE_PORT:5432}/postgres
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:zaranik}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
#    validateOnMigrate: false
#    locations:
#      - classpath:db/migration

auth-service:
  url: http://${AUTH_SERVICE_HOST:localhost}:${AUTH_SERVICE_PORT:8081}/api/auth/validate