server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/booking-service
    username: admin
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
#    validateOnMigrate: false
#    locations:
#      - classpath:db/migration