server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/booking-service
    username: admin
    password: admin
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: db/changelog/db.changelog-master.xml