server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://${BOOKING_POSTGRES_SERVICE_HOST:localhost}:${BOOKING_POSTGRES_SERVICE_PORT:5432}/booking-service
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:admin}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    url: jdbc:postgresql://${BOOKING_POSTGRES_SERVICE_HOST:localhost}:${BOOKING_POSTGRES_SERVICE_PORT:5432}/booking-service
    user: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:admin}
#    validateOnMigrate: false
#    locations:
#      - classpath:db/migration

auth-service:
  url: http://${AUTH_SERVICE_HOST:localhost}:${AUTH_SERVICE_PORT:8082}/api/auth/validate
movie-management-service:
  url: http://${MOVIE_MANAGEMENT_SERVICE_HOST:localhost}:${MOVIE_MANAGEMENT_SERVICE_PORT:8081}/api/movie-management
