server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/booking-service
    username: postgres
    password: zaranik
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    url: jdbc:postgresql://localhost:5432/booking-service
    user: postgres
    password: zaranik

auth-service:
  url: http://192.168.49.2:8081/api/auth/validate