apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - http:
        paths:
          - path: {{ .Values.ingress.mapping }}
            pathType: "Prefix"
            backend:
              service:
                name: {{ .Chart.Name }}
                port:
                  {{- range .Values.service.ports }}
                    number: {{ .port }}
                  {{- end }}