replicaCount: 1

image:
  name: zaranik/email:3.4
  port: 8083

service:
  ports:
    - name: http
      port: 80
      targetPort: 8083

resources:
  limits:
    memory: "300Mi"
    cpu: "250m"

env:
  - name: FROM_EMAIL_VALUE
    type: secret
    value: FROM_EMAIL_VALUE
  - name: EMAIL_KEY
    type: secret
    value: EMAIL_KEY