apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}-pod
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}-pod
    spec:
      containers:
        - image: zaranik/email-service:3.1
          name: {{ .Release.Name }}-{{ .Chart.Name }}-container
          ports:
            - containerPort: 8083
          resources:
            limits:
              memory: "512Mi"
              cpu: "250m"
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
                  key: POSTGRES_PASSWORD
            - name: FROM_EMAIL_VALUE
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
                  key: FROM_EMAIL_VALUE
            - name: EMAIL_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
                  key: EMAIL_KEY                  
