apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "common.name" .}}-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: "Prefix"
            backend:
              service:
                name: {{ .Chart.Name }}
                port:
                  number: {{ .Values.ingress.port }}