apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
spec:
  type: ClusterIP
  ports:
  {{- range $key, $value := .Values.service.ports }}
    - name: {{ $value.name }}
      port: {{ $value.port }}
      targetPort: {{ $value.name }}
    {{- end }}
  selector:
    app: {{ .Values.selector.app }}
