apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-management-postgres-deployment
spec:
  selector:
    matchLabels:
      app: movie-management-postgres-pod
  template:
    metadata:
      labels:
        app: movie-management-postgres-pod
    spec:
      containers:
        - name: movie-management-container
          image: postgres:14.1-alpine3.15
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-db
          resources:
            limits:
              memory: "512Mi"
              cpu: "250m"
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: movie-management-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: movie-management-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: movie-management-secret
                  key: POSTGRES_PASSWORD
      volumes:
        - name: postgres-db
          persistentVolumeClaim:
            claimName: movie-management-service-claim
