replicaCount: 1

image:
  name: secret333boy/auth:2.0
  port: 8082

service:
  ports:
    - name: http
      port: 80
      containerPort: 8082
      
resources:
  limits:
    memory: "512Mi"
    cpu: "250m"

gateway:
  url: "http://192.168.49.2:80"

ingress:
  mapping: /api/auth

db:
  storage: "512Mi"
  resources:
    limits:
      memory: "512Mi"
      cpu: "250m"
  containerPort: 5432
  servicePort: 5432
  volumeMount: /var/lib/postgresql/data
  image: postgres:14.1-alpine3.15