replicaCount: 1

image:
  name: secret333boy/auth:2.0
  port: 8082

service:
  ports:
    - name: http
      port: 80
      targetPort: 8082

resources:
  limits:
    memory: "512Mi"
    cpu: "250m"

gateway:
  url: "http://192.168.49.2:80"

ingress:
  mapping: /api/auth

postgresql:
  nameOverride: auth-postgres
  fullnameOverride: auth-postgres
  postgresqlDatabase: "postgres"
  postgresqlUsername: "postgres"
  postgresqlPassword: "postgres"
  postgresqlPostgresPassword: "postgres"
  persistence:
    size: 1Gi
    mountPath: /var/lib/postgresql/data
