apiVersion: networking.k8s.io/v1
kind: Ingress
<<<<<<< HEAD:helm_booking/v3/charts/booking/templates/ingress.yaml
metadata:
  name: booking-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: "Prefix"
            backend:
              service:
                name: booking
                port:
                  number: {{ .Values.ingress.port }}
=======
{{ include "common.ingress" . }}
>>>>>>> origin/master:helm/v1/charts/auth/templates/ingress.yaml
