apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-deployment
  labels:
    app: email
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email
  template:
    metadata:
      labels:
        app: email
    spec:
      containers:
        - name: email
          image: secret333boy/email:1.0
          ports:
            - containerPort: 8083
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: email
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8083
  selector:
    app: email
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
  labels:
    name: myingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    # - host: myapp.com
    - http:
        paths:
          - path: /email
            pathType: Prefix
            backend:
              service:
                name: email
                port:
                  number: 80
