apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-pod
  template:
    metadata:
      labels:
        app: email-pod
    spec:
      containers:
        - image: zaranik/email-service:3.1
          name: email-container
          ports:
            - containerPort: 8083
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: email-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: email-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: email-secret
                  key: POSTGRES_PASSWORD
            - name: FROM_EMAIL_VALUE
              valueFrom:
                secretKeyRef:
                  name: email-secret
                  key: FROM_EMAIL_VALUE
            - name: EMAIL_KEY
              valueFrom:
                secretKeyRef:
                  name: email-secret
                  key: EMAIL_KEY                  
