apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-postgres-deployment
spec:
  selector:
    matchLabels:
      app: booking-postgres-pod
  template:
    metadata:
      labels:
        app: booking-postgres-pod
    spec:
      containers:
        - name: booking-container
          image: postgres:14.1-alpine3.15
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-db
          resources:
            limits:
              memory: "512Mi"
              cpu: "250m"
          envFrom:
            - configMapRef:
                name: booking-config
            - secretRef:
                name: booking-secret
      volumes:
        - name: postgres-db
          persistentVolumeClaim:
            claimName: booking-service-claim