apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.name" . }}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "common.name" . }}-pod
  template:
    metadata:
      labels:
        app: {{ include "common.name" . }}-pod
    spec:
      initContainers:
        - name: {{ include "common.name" . }}-migration
          image: secret333boy/auth-migrations:1.2
          command: ["db-migrate", "up", "--config", "database.json", "-e", "prod"]
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ include "common.name" . }}-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "common.name" . }}-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "common.name" . }}-secret
                  key: POSTGRES_PASSWORD
            - name: AUTH_POSTGRES_SERVICE_HOST
              value: {{ include "common.name" . }}-postgres
            - name: AUTH_POSTGRES_SERVICE_PORT
              value: "5432"
      containers:
        - image: {{ .Values.image.name }}
          name: {{ include "common.name" . }}-container
          ports:
            - containerPort: {{ .Values.image.port }}
          env:
            - name: GATEWAY_URL
              value: {{ .Values.gateway.url }}
            - name: PASSWORD_SALT
              valueFrom:
                secretKeyRef:
                  name: {{ include "common.name" . }}-secret
                  key: PASSWORD_SALT
            - name: ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "common.name" . }}-secret
                  key: ACCESS_TOKEN_SECRET
            - name: REFRESH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "common.name" . }}-secret
                  key: REFRESH_TOKEN_SECRET
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ include "common.name" . }}-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "common.name" . }}-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "common.name" . }}-secret
                  key: POSTGRES_PASSWORD
            - name: AUTH_POSTGRES_SERVICE_HOST
              value: {{ include "common.name" . }}-postgres
            - name: AUTH_POSTGRES_SERVICE_PORT
              value: "5432"
          resources:
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
