apiVersion: apps/v1
kind: Deployment
metadata:
  name: service4-deployment
  labels:
    app: service4
spec:
  selector:
    matchLabels:
      app: service4
  template:
    metadata:
      labels:
        app: service4
    spec:
      containers:
      - name: service4
        image: secret333boy/service4:1.0
        ports:
        - containerPort: 84