replicaCount: 1

image:
  name: zaranik/movie-management:2.80
  port: 8081

service:
  ports:
    - name: http
      port: 80
      targetPort: 8081

resources:
  limits:
    memory: "512Mi"
    cpu: "500m"

env:
  - name: POSTGRES_DB
    type: secret
    value: POSTGRES_DB
  - name: POSTGRES_USER
    type: secret
    value: POSTGRES_USER
  - name: POSTGRES_PASSWORD
    type: secret
    value: POSTGRES_PASSWORD

ingress:
  mapping: /api/movie-management

db:
  port: "5432"

postgresql:
  nameOverride: movie-management-postgres
  fullnameOverride: movie-management-postgres
  postgresqlDatabase: "movie-management"
  postgresqlUsername: "postgres"
  postgresqlPassword: "postgres"
  postgresqlPostgresPassword: "postgres"
  persistence:
    size: 1Gi
    mountPath: /var/lib/postgresql/data
