apiVersion: v1
kind: Secret
metadata:
  name: email-secret
type: Opaque
data:
  POSTGRES_DB: cG9zdGdyZXM=
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  FROM_EMAIL_VALUE: emFyYW5pa2J6QGdtYWlsLmNvbQ==
  EMAIL_KEY: ZmNpZWJmc3dhbWlna3N4aQ==