-- liquibase formatted sql

CREATE TABLE cinema
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255),
    location VARCHAR(255),
    CONSTRAINT pk_cinema PRIMARY KEY (id)
);

CREATE TABLE cinema_feedback
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id   BIGINT,
    cinema_id BIGINT,
    score     INTEGER,
    comment   VARCHAR(255),
    CONSTRAINT pk_cinema_feedback PRIMARY KEY (id)
);

CREATE TABLE hall
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(255),
    cinema_id BIGINT,
    CONSTRAINT pk_hall PRIMARY KEY (id)
);

CREATE TABLE movie
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    image_path  VARCHAR(255),
    duration    BIGINT,
    CONSTRAINT pk_movie PRIMARY KEY (id)
);

CREATE TABLE movie_feedback
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id  BIGINT,
    movie_id BIGINT,
    score    INTEGER,
    comment  VARCHAR(255),
    CONSTRAINT pk_moviefeedback PRIMARY KEY (id)
);

CREATE TABLE place
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    hall_id      BIGINT,
    row          BIGINT,
    place_number BIGINT,
    CONSTRAINT pk_place PRIMARY KEY (id)
);

ALTER TABLE cinema_feedback
    ADD CONSTRAINT FK_CINEMA_FEEDBACK_ON_CINEMA FOREIGN KEY (cinema_id) REFERENCES cinema (id);

ALTER TABLE hall
    ADD CONSTRAINT FK_HALL_ON_CINEMA FOREIGN KEY (cinema_id) REFERENCES cinema (id);

ALTER TABLE movie_feedback
    ADD CONSTRAINT FK_MOVIEFEEDBACK_ON_MOVIE FOREIGN KEY (movie_id) REFERENCES movie (id);

ALTER TABLE place
    ADD CONSTRAINT FK_PLACE_ON_HALL FOREIGN KEY (hall_id) REFERENCES hall (id);

