create table ticket (
    id bigint generated by default not null,
    price double not null,
    user_id bigint default null,
    session_id bigint not null,
    place_id bigint not null,
    constraint pk_ticket primary key (id)
);

create table session (
    id bigint generated by default not null,
    movie_id bigint not null,
    hall_id bigint not null,
    start_time date,
    end_time date,
    constraint pk_session primary key (id)
);

alter table ticket
    add constraint fk_ticket_on_session
    foreign key (session_id)
    references session (id);