apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-deployment
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}-pod
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}-pod
    spec:
      containers:
        - image: 96223961382/movie-management-service:2.7
          name: {{ .Release.Name }}-{{ .Chart.Name }}-container
          ports:
            - containerPort: 8081
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
                  key: POSTGRES_PASSWORD
          resources:
            limits:
              memory: "512Mi"
              cpu: "250m"