apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
  labels:
    app: {{ .Chart.Name }}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-pod
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-pod
    spec:
      containers:
        - image: 96223961382/movie-management-service:2.7
          name: {{ .Chart.Name }}-container
          ports:
            - containerPort: 8081
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-secret
                  key: POSTGRES_PASSWORD
            - name: MOVIE_MANAGEMENT_POSTGRES_SERVICE_HOST
              value: movie-management-postgres
            - name: MOVIE_MANAGEMENT_POSTGRES_SERVICE_PORT
              value: "5432"
          resources:
            limits:
              memory: "512Mi"
              cpu: "250m"