apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.name" . }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8081
  selector:
    app: {{ include "common.name" . }}-pod
