apiVersion: apps/v1
kind: Deployment
metadata:
  name: service3-deployment
  labels:
    app: service3
spec:
  selector:
    matchLabels:
      app: service3
  template:
    metadata:
      labels:
        app: service3
    spec:
      containers:
      - name: service3
        image: secret333boy/service3:1.0
        ports:
        - containerPort: 83